add Discord.TextChannel type before calling send
fixes "error TS2339: Property 'send' does not exist on type 'Channel'." when I run `yarn build-tsc`. Dunno if this is necessary -- certainly doesn't seem needed on Tal's machine.